### ISSUE TITLE
Price filter could show price range

### ISSUE THREAD

**Issue by jamdelion** [fac22/week6-MAD#44]
From a usability perspective, I don't think the price filter is particularly easy to use - the user has no idea what the upper and lower ranges of product prices are.Perhaps you could consider displaying the price range and get it to chance dynamically when the filter sliders are moved.

**Comment by lopezelpesado** [comment]
Absolutely! Totally not useful at the moment 🤦‍♂️ I've added an output element to each slider that updates as they change.
